from fpdf import FPDF  # type: ignore
import os
from xhtml2pdf import pisa # type: ignore


# pdf_generator.py
from xhtml2pdf import pisa # import pisa function from xhtml2pdf library
import os

# Function to convert HTML content to PDF
def convert_html_to_pdf(html_content, output_filename):
    """
    Converts a string of HTML content into a PDF file.

    Args:
        html_content (str): The HTML content to convert.
        output_filename (str): The path where the PDF file will be saved.

    Returns:
        bool: True if conversion was successful, False otherwise.
    """
    try:
        # Open the output file in write-binary mode
        with open(output_filename, "wb") as pdf_file:
            # Convert HTML to PDF
            pisa_status = pisa.CreatePDF(
                html_content, # The HTML content string
                dest=pdf_file # The file handle to write to
            )

        # Check if PDF creation was successful
        if pisa_status.err:
            print(f"❌ Error during PDF generation: {pisa_status.err}")
            return False
        else:
            print(f"✅ PDF successfully generated: {output_filename}")
            return True
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")
        # Attempt to remove partially created file on error
        if os.path.exists(output_filename):
            try:
                os.remove(output_filename)
            except OSError:
                pass # Ignore errors during cleanup
        return False

# Main PDF generation function called by main.py
# We keep the same function name and signature for compatibility
def generate_pdf(content, filename):
    """
    Wrapper function to maintain compatibility with main.py.
    Calls the HTML-to-PDF conversion function.

    Args:
        content (str): The HTML content generated by the AI service.
        filename (str): The desired output path for the PDF file.
    """
    # Ensure the directory exists (though main.py already does this)
    output_dir = os.path.dirname(filename)
    if not os.path.exists(output_dir):
        try:
            os.makedirs(output_dir)
        except OSError as e:
            print(f"❌ Could not create directory {output_dir}: {e}")
            return

    # Call the conversion function
    success = convert_html_to_pdf(content, filename)
    if not success:
        print(f"⚠️ Failed to generate PDF: {filename}")
        # Optionally: Handle the failure case further if needed